In [2]:
import pandas as pd
import numpy as np

In [3]:
obj = pd.Series([4, 7, -5, 3], index=["d" ,"b", "a", "c"])
obj.dtypes

dtype('int64')

In [4]:
data = {
    "state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
    "year" : [2000, 2001, 2002, 2001, 2002, 2003],
    "pop"  : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [5]:
frame['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [6]:
frame['Country'] = "US"
frame

    state  year  pop Country
0    Ohio  2000  1.5      US
1    Ohio  2001  1.7      US
2    Ohio  2002  3.6      US
3  Nevada  2001  2.4      US
4  Nevada  2002  2.9      US
5  Nevada  2003  3.2      US

In [7]:
frame['eastern'] = frame.state == 'Ohio'
frame

    state  year  pop Country  eastern
0    Ohio  2000  1.5      US     True
1    Ohio  2001  1.7      US     True
2    Ohio  2002  3.6      US     True
3  Nevada  2001  2.4      US    False
4  Nevada  2002  2.9      US    False
5  Nevada  2003  3.2      US    False

In [8]:
data_with_nan = pd.Series([1, np.nan, 3.5, np.nan, 7])
print("Original data:")
display(data_with_nan)

print("\nWhich values are missing?")
display(data_with_nan.isna())

print("\nWhich values are NOT missing?")
display(data_with_nan.notna())

Original data:

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

Which values are missing?

0    False
1     True
2    False
3     True
4    False
dtype: bool

Which values are NOT missing?

0     True
1    False
2     True
3    False
4     True
dtype: bool

In [9]:
# Activity: The Inventory System

# [EXERCISE] Starter Code
fruit_data = {
    "fruit": ["Apple", "Banana", "Cherry", "Date"],
    "quantity": [100, 40, 200, 20]
}

# 1. Create DataFrame
inventory = pd.DataFrame(fruit_data)

# 2. Add Price
inventory['price'] = [3.0, 4.0, 2.0, 5.0]

# 3. Calculate Total Value
inventory['total_price'] = inventory['quantity'] * inventory['price']

# 4. Flag Low Stock
inventory['low_stock'] = inventory['quantity'] < 50

# Display result
inventory

    fruit  quantity  price  total_price  low_stock
0   Apple       100    3.0        300.0      False
1  Banana        40    4.0        160.0       True
2  Cherry       200    2.0        400.0      False
3    Date        20    5.0        100.0       True

# SECTION 2: Indexinng & Selection
1. .loc
2. .iloc
3. data[data["columm/row"] > 3]
4. data[["column"], ["row"]]

In [10]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [11]:
data.loc['Colorado']

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [12]:
# [DEMO] Select 'Colorado' row using loc
print("--- Row by Label ---")
display(data.loc["Colorado"])

# [DEMO] Select 'Colorado' row using iloc (it's at index 1)
print("\n--- Row by Position ---")
display(data.iloc[1]) # [:, 0] all rows first column

--- Row by Label ---

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

--- Row by Position ---

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [13]:
data[data['three'] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [14]:
# [DEMO] Dropping rows and columns
print("Drop rows 'Colorado' and 'Ohio':")
display(data.drop(["Colorado", "Ohio"]))

print("\nDrop column 'two':")
display(data.drop("two", axis=1))

Drop rows 'Colorado' and 'Ohio':

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

Drop column 'two':

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [34]:
# [EXERCISE] Write your code here
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
# 1. Utah and New York

display(data.loc[["Utah", "New York"]])

# 2. 'two' for 'Ohio'
display(data.loc[['Ohio'], ['two']])

# 3. Filter > 5
mask = data["three"] > 5
display(data[mask])

# 4. Update value
# data.iloc[-1, -1] = 100
data.loc["New York", "four"] = 100

data

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

      two
Ohio    1

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14   100

# SECTION 3: Function Application, Sorting & Ranking
1. sort_index()
2. sort_values(by=...)
3. rank()
4. .apply() Vectorized operations are faster than loops. Use .apply() for custom logic.

In [16]:
# Setup Data
frame = pd.DataFrame({
    "b": [4, 7, -3, 2], 
    "a": [0, 1, 0, 1]
}, index=['Row1', 'Row2', 'Row3', 'Row4'])
frame

      b  a
Row1  4  0
Row2  7  1
Row3 -3  0
Row4  2  1

In [17]:
new_frame = frame.sort_values(by="b")
new_frame

      b  a
Row3 -3  0
Row4  2  1
Row1  4  0
Row2  7  1

In [18]:
frame = new_frame.sort_index()

In [19]:
def label_size(value):
    return "Big" if value > 2 else "Small"

frame['b_size'] = frame['b'].apply(label_size)
frame

      b  a b_size
Row1  4  0    Big
Row2  7  1    Big
Row3 -3  0  Small
Row4  2  1  Small

In [37]:
# [EXERCISE] Starter Code
# 1. Run the starter code to generate the scores DataFrame.
scores = pd.DataFrame({
    "Student": ["Alice", "Bob", "Charlie", "David"],
    "Math": [85, 45, 92, 60],
    "Science": [70, 55, 88, 72]
})

scores

# 2. Sort the DataFrame by 'Math' score in descending order (highest first).
scores.sort_values(by='Math', ascending=False)

# 3. Create a new column 'Math_Rank' using the .rank() method.
scores['Math_Rank'] = scores['Math'].rank(method="min", ascending=False).astype(int)
scores

# 4. Define a function that returns "Pass" if score >= 60 and "Fail" otherwise.
def pass_fail(value) -> str:
    return "Pass" if value >= 60 else "Fail"

# 5. Apply this function to the 'Math' column to create a new 'Status' column.
scores['Math_Status'] = scores["Math"].apply(pass_fail)

scores

   Student  Math  Science  Math_Rank Math_Status
0    Alice    85       70          2        Pass
1      Bob    45       55          4        Fail
2  Charlie    92       88          1        Pass
3    David    60       72          3        Pass